# Spring Boot Configuration
spring.application.name=climalert
server.port=8080

# Weather API Configuration - ¡ACÁ VA LO REAL!
climalert.weather.api.key=38aa8635727744c686020938260707
climalert.weather.api.location=CABA
climalert.weather.api.url=http://api.weatherapi.com/v1/current.json

# Mail Configuration - Para probar el envío real de mails localmente (ej: usando Mailpit o GreenMail)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Configuración de destinatarios para las alertas
climalert.notificaciones.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

# Cambialo a true cuando quieras que intente conectar al servidor SMTP real de arriba
climalert.email.enabled=true

# Parámetros de negocio para la detección de alertas
climalert.alertas.temperatura-critica=35.0
climalert.alertas.humedad-critica=60.0
